WARNING basehttp 2024-03-14 14:10:04,655 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:10:55,777 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:11:24,785 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:11:52,785 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
INFO views 2024-03-14 14:17:33,923 C:\Users\user1\django_projects\event_project\event_manager\events\views.pySuchwort war as
WARNING basehttp 2024-03-14 14:17:34,065 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:18:47,587 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:18:50,942 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:18:53,844 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:19:07,875 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:19:23,562 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:19:24,884 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:29:05,898 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 14:29:06,043 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 14:29:09,160 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:29:22,565 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:34:02,650 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:34:14,689 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:41,803 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:43,495 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:48,344 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:49,954 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:56,428 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:36:59,212 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:37:06,550 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:37:17,240 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:39:44,344 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:40:04,541 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:41:22,212 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:41:34,300 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 14:43:52,502 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 14:43:52,644 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 14:44:03,059 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:27:39,478 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:29:08,786 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:30:27,983 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:30:42,715 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:33:35,739 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:33:41,312 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:34:10,874 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:34:18,293 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:34:46,513 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:35:13,689 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:35:15,570 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:35:49,654 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:35:51,090 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:35:51,180 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:35:52,279 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:35:56,567 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:36:03,962 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:36:04,053 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:36:05,075 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:36:06,809 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:36:11,279 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:36:19,715 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:36:19,804 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:36:39,162 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:37:00,119 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:37:01,440 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:37:02,840 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:37:02,922 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:37:04,577 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:37:08,229 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:37:12,371 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:37:47,764 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:37:49,972 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:37:51,773 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /media/images/test.txt
WARNING basehttp 2024-03-14 15:37:51,774 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /media/images/test.txt HTTP/1.1" 404 12225
WARNING log 2024-03-14 15:38:01,358 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:38:09,902 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:38:11,663 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /media/images/test.txt
WARNING basehttp 2024-03-14 15:38:11,664 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /media/images/test.txt HTTP/1.1" 404 12225
WARNING log 2024-03-14 15:38:31,866 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING log 2024-03-14 15:38:34,106 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:39:01,598 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:39:51,469 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:39:53,972 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:39:58,912 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:41:36,662 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:41:37,802 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:41:38,621 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:43:38,891 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:44:03,332 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:44:05,485 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:46:30,157 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:46:32,495 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:46:33,487 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
ERROR log 2024-03-14 15:46:40,833 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /events/category/create
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\events\views.py", line 165, in category_create
    print("request:", request["FILES"])
                      ~~~~~~~^^^^^^^^^
TypeError: 'WSGIRequest' object is not subscriptable
ERROR basehttp 2024-03-14 15:46:40,866 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /events/category/create HTTP/1.1" 500 78199
WARNING basehttp 2024-03-14 15:46:55,080 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:49:25,067 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:49:25,228 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
WARNING basehttp 2024-03-14 15:49:25,987 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:49:30,994 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:50:50,387 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:50:51,450 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
ERROR log 2024-03-14 15:51:15,819 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /events/category/create
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\events\views.py", line 176, in category_create
    return redirect(category)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\shortcuts.py", line 49, in redirect
    return redirect_class(resolve_url(to, *args, **kwargs))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\shortcuts.py", line 180, in resolve_url
    return reverse(to, args=args, kwargs=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'events.views.category' not found. 'events.views.category' is not a valid view function or pattern name.
ERROR basehttp 2024-03-14 15:51:15,863 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /events/category/create HTTP/1.1" 500 96250
WARNING basehttp 2024-03-14 15:53:02,734 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:54:02,924 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-14 15:54:04,981 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-14 15:55:15,769 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /media/images/test3.txt
WARNING basehttp 2024-03-14 15:55:15,769 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /media/images/test3.txt HTTP/1.1" 404 12229
WARNING log 2024-03-14 15:55:26,247 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /media/images/test3.txt
WARNING basehttp 2024-03-14 15:55:26,248 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /media/images/test3.txt HTTP/1.1" 404 12229
WARNING basehttp 2024-03-15 08:59:44,265 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 08:59:47,785 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:03:52,659 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:04:34,369 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:06:44,898 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:06:59,911 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:07:01,461 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:07:20,954 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:09:05,838 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:10:12,470 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:10:13,863 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:10:41,948 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:11:36,954 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:11:39,341 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:16:43,464 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:16:45,979 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:16:47,514 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:16:50,086 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:17:28,983 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:17:31,356 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:17:35,303 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:17:58,172 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:18:51,464 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:18:54,377 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:33:57,953 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:50:18,863 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 09:50:25,915 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:40,539 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:42,095 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:42,574 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:49,957 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:52,147 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:54,341 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:21:55,339 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:22:17,130 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:26:13,406 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:27:49,737 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:38:39,132 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:38:57,714 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:39:16,609 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:46:57,267 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:46:58,490 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:47:00,941 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:47:03,899 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:47:04,655 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 10:47:11,413 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:16,285 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:19,042 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:22,232 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:24,027 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:24,891 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:26,008 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:27,354 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:28,423 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:01:30,804 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:55:45,499 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:38,612 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:41,306 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:43,665 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:45,047 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:46,474 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:47,512 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:48,644 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:49,020 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:49,669 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:50,224 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:56:51,094 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 11:58:15,191 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
ERROR log 2024-03-15 11:59:45,490 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /events/
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'yesno::"bg-success,bg-error"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 24: 'yesno::"bg-success,bg-error"', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR basehttp 2024-03-15 11:59:45,564 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /events/ HTTP/1.1" 500 205867
WARNING log 2024-03-15 11:59:45,688 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
ERROR log 2024-03-15 12:00:12,522 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /events/
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'event.is_active|yesno:"bg-success,bg-error"'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\template\base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 24: 'event.is_active|yesno:"bg-success,bg-error"', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR basehttp 2024-03-15 12:00:12,574 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /events/ HTTP/1.1" 500 206072
WARNING basehttp 2024-03-15 12:01:03,735 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:01:20,736 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:01:40,923 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:02:04,060 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:02:18,726 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:02:42,322 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:02:43,479 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:03:18,733 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:03:21,130 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:05:34,351 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:05:39,096 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:17:54,927 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:05,292 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:09,043 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:17,495 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:20,554 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:21,803 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-15 12:18:40,324 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /events/
WARNING basehttp 2024-03-15 12:18:40,324 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /events/?page=2 HTTP/1.1" 404 12074
WARNING basehttp 2024-03-15 12:18:46,763 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:18:52,729 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:19:06,634 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:19:18,155 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:19:22,683 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:19:26,395 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:20:04,075 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:20:16,473 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:20:19,689 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:20:21,836 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:40,904 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:43,279 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:46,732 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:48,183 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:51,817 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:21:54,959 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:22:23,863 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:22:35,604 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:22:47,319 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:25:32,819 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:25:34,772 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:25:36,513 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:25:37,683 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:26:13,484 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:26:15,620 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:26:22,275 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:18,956 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:20,334 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:37,203 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:39,079 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:40,539 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:43,368 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:45,643 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:27:46,491 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:28:17,507 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:28:21,268 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:28:29,106 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 12:29:17,241 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
ERROR log 2024-03-15 13:25:17,208 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 210, in _get_response
    response = middleware_method(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\event_manager\middleware.py", line 23, in process_template_response
    response.context_data["current_timestamp"] = timezone.now()
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
ERROR basehttp 2024-03-15 13:25:17,255 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 500 77066
WARNING basehttp 2024-03-15 13:26:03,330 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 13:26:29,875 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 13:26:40,317 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-15 13:26:45,625 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /api/events/
WARNING basehttp 2024-03-15 13:26:45,625 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events/ HTTP/1.1" 404 12185
WARNING log 2024-03-15 13:26:49,353 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /api/events
WARNING basehttp 2024-03-15 13:26:49,353 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 404 12181
ERROR log 2024-03-15 13:27:04,676 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 210, in _get_response
    response = middleware_method(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\event_manager\middleware.py", line 23, in process_template_response
    response.context_data["current_timestamp"] = timezone.now()
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
ERROR basehttp 2024-03-15 13:27:04,728 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 500 77066
ERROR log 2024-03-15 13:28:02,545 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\mixins.py", line 46, in list
    return Response(serializer.data)
                    ^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 768, in data
    ret = super().data
          ^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 687, in to_representation
    self.child.to_representation(item) for item in iterable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 507, in to_representation
    for field in fields:
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 1076, in get_fields
    field_class, field_kwargs = self.build_field(
                                ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 1222, in build_field
    return self.build_unknown_field(field_name, model_class)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 1340, in build_unknown_field
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Field name `slug` is not valid for model `Event`.
ERROR basehttp 2024-03-15 13:28:02,618 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 500 159943
ERROR log 2024-03-15 13:28:13,873 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 210, in _get_response
    response = middleware_method(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\event_manager\middleware.py", line 23, in process_template_response
    response.context_data["current_timestamp"] = timezone.now()
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
ERROR basehttp 2024-03-15 13:28:13,930 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 500 77066
ERROR log 2024-03-15 13:28:26,933 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 210, in _get_response
    response = middleware_method(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\event_manager\middleware.py", line 23, in process_template_response
    response.context_data["current_timestamp"] = timezone.now()
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object does not support item assignment
ERROR basehttp 2024-03-15 13:28:26,998 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events HTTP/1.1" 500 77066
WARNING log 2024-03-15 13:32:46,184 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:32:46,184 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 21880
WARNING log 2024-03-15 13:33:09,858 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:33:09,858 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 22296
WARNING basehttp 2024-03-15 13:33:19,098 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING basehttp 2024-03-15 13:33:23,277 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-15 13:33:42,975 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:33:42,976 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 22296
WARNING log 2024-03-15 13:34:05,492 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:34:05,492 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 22078
WARNING log 2024-03-15 13:36:32,723 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:36:32,723 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 49
WARNING log 2024-03-15 13:37:04,884 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 13:37:04,884 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 49
WARNING log 2024-03-15 13:42:37,516 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events/179
WARNING basehttp 2024-03-15 13:42:37,516 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"PUT /api/events/179 HTTP/1.1" 400 24261
WARNING log 2024-03-15 13:43:55,943 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events/179
WARNING basehttp 2024-03-15 13:43:55,943 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"PUT /api/events/179 HTTP/1.1" 400 224
WARNING log 2024-03-15 13:45:41,372 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /api/events/179
WARNING basehttp 2024-03-15 13:45:41,372 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events/179 HTTP/1.1" 404 23193
WARNING basehttp 2024-03-15 13:50:33,122 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /static/images/penglogo.png HTTP/1.1" 404 1816
WARNING log 2024-03-15 13:50:42,545 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /api/events/187
WARNING basehttp 2024-03-15 13:50:42,545 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events/187 HTTP/1.1" 404 14926
WARNING log 2024-03-15 13:50:45,923 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /api/events/
WARNING basehttp 2024-03-15 13:50:45,923 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events/ HTTP/1.1" 404 12572
WARNING log 2024-03-15 13:51:36,368 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyForbidden: /api/events/150
WARNING basehttp 2024-03-15 13:51:36,368 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"PATCH /api/events/150 HTTP/1.1" 403 33
WARNING log 2024-03-15 13:56:08,503 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyMethod Not Allowed: /api/token
WARNING basehttp 2024-03-15 13:56:08,503 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/token HTTP/1.1" 405 43
WARNING log 2024-03-15 13:56:16,949 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/token
WARNING basehttp 2024-03-15 13:56:16,949 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/token HTTP/1.1" 400 91
WARNING log 2024-03-15 13:56:51,248 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyMethod Not Allowed: /api/token
WARNING basehttp 2024-03-15 13:56:51,248 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"-d /api/token HTTP/1.1" 405 42
WARNING log 2024-03-15 13:57:03,607 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/token
WARNING basehttp 2024-03-15 13:57:03,607 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/token HTTP/1.1" 400 68
WARNING log 2024-03-15 14:03:40,180 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyForbidden: /api/events/150
WARNING basehttp 2024-03-15 14:03:40,180 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"PATCH /api/events/150 HTTP/1.1" 403 33
WARNING log 2024-03-15 14:13:41,583 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyForbidden: /api/events
WARNING basehttp 2024-03-15 14:13:41,583 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 403 33
WARNING log 2024-03-15 14:14:11,093 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 14:14:11,093 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 44
ERROR log 2024-03-15 14:15:07,928 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\generics.py", line 242, in post
    return self.create(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\mixins.py", line 18, in create
    serializer.is_valid(raise_exception=True)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 479, in to_internal_value
    for field in fields:
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 362, in _writable_fields
    for field in self.fields.values():
                 ^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 1052, in get_fields
    field_names = self.get_field_names(declared_fields, info)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\serializers.py", line 1117, in get_field_names
    assert not (fields and exclude), (
AssertionError: Cannot set both 'fields' and 'exclude' options on serializer EventSerializer.
ERROR basehttp 2024-03-15 14:15:07,975 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 500 147302
WARNING log 2024-03-15 14:16:35,349 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyBad Request: /api/events
WARNING basehttp 2024-03-15 14:16:35,349 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"POST /api/events HTTP/1.1" 400 44
WARNING log 2024-03-15 14:20:55,873 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyNot Found: /favicon.ico
ERROR log 2024-03-15 14:28:28,424 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\utils\log.pyInternal Server Error: /api/events/150
Traceback (most recent call last):
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\generics.py", line 282, in get
    return self.retrieve(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\generics.py", line 99, in get_object
    self.check_object_permissions(self.request, obj)
  File "C:\Users\user1\django_projects\eventenv\Lib\site-packages\rest_framework\views.py", line 345, in check_object_permissions
    if not permission.has_object_permission(request, self, obj):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user1\django_projects\event_project\event_manager\events\api\permissions.py", line 11, in has_object_permission
    return is_owner or self.request.method in permissions.SAFE_METHODS
                       ^^^^^^^^^^^^
AttributeError: 'IsOwnerOrReadonly' object has no attribute 'request'
ERROR basehttp 2024-03-15 14:28:28,487 C:\Users\user1\django_projects\eventenv\Lib\site-packages\django\core\servers\basehttp.py"GET /api/events/150 HTTP/1.1" 500 119852
